window.AppDefaults = {
  settings: {
    totalPortfolioValue: 3000000,
    coreValue: 2100000,
    satelliteTargetPercent: 30,
    maxSingleStockSatellitePercent: 20,
    maxSingleStockTotalPercent: 6,
    maxThemeSatellitePercent: 50,
    researchOutdatedDays: 90,
    baseCurrency: "TWD",
    supportedCurrencies: ["TWD", "USD"],
    exchangeRates: { TWD: 1, USD: 1 },
    exchangeRateUpdatedAt: ""
  },
  watchlistStocks: [
    {
      id: "stock-tsm",
      ticker: "TSM",
      companyName: "Taiwan Semiconductor",
      currency: "USD",
      market: "美國",
      industry: "半導體",
      tags: ["AI", "先進製程", "晶圓代工"],
      stage: "正常持有",
      thesis: "先進製程領先，AI 運算需求支撐長期成長。",
      risk: "地緣政治與高額資本支出。",
      invalidation: "先進製程市占連續兩季明顯下滑。",
      fairPriceRange: "US$ 145-175",
      nextReviewDate: "2026-06-10",
      lastUpdatedDate: "2026-05-28"
    },
    {
      id: "stock-aapl",
      ticker: "AAPL",
      companyName: "Apple Inc.",
      currency: "USD",
      market: "美國",
      industry: "消費電子",
      tags: ["品牌", "服務收入"],
      stage: "深入研究",
      thesis: "生態系黏著度高，服務業務具持續成長空間。",
      risk: "硬體換機週期放緩與監管壓力。",
      invalidation: "服務收入成長率連續三季低於 5%。",
      fairPriceRange: "US$ 175-195",
      nextReviewDate: "2026-06-18",
      lastUpdatedDate: "2026-06-01"
    },
    {
      id: "stock-cost",
      ticker: "COST",
      companyName: "Costco Wholesale",
      currency: "USD",
      market: "美國",
      industry: "零售",
      tags: ["會員制", "防禦型消費"],
      stage: "等待合理價格",
      thesis: "會員續約率高，商業模式帶來穩定現金流。",
      risk: "目前估值偏高，報酬空間受到壓縮。",
      invalidation: "會員續約率低於 88%。",
      fairPriceRange: "US$ 700-760",
      nextReviewDate: "2026-06-25",
      lastUpdatedDate: "2026-05-20"
    }
  ],
  positions: [],
  transactions: [],
  journalEntries: [],
  investmentReviews: [],
  investmentLessons: [],
  personalFinanceSchemaVersion: 2,
  financialAccounts: [],
  accountBalances: [],
  insurancePolicies: [],
  liabilities: [],
  incomeCategories: [],
  expenseCategories: [],
  cashFlowEntries: [],
  recurringCashFlows: [],
  monthlyBudgets: []
};
